name:                language-bender
version:             0.1.0.0
github:              "jesuswr/Doe-Lang"
license:             BSD3
author:              
  - "Jesús Wahrman"
  - "Neil Villamizar"
  - "Luis Diaz"
maintainer:          
  - "ldiazn98@gmail.com"
copyright:           "2021 Jesús Wahrman"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/jesuswr/Doe-Lang>

dependencies:
- base >= 4.7 && < 5
- array
- directory
- hspec
- extra

library:
  source-dirs: src
  build-tools:
    - alex
    - happy
    - hlint

executables:
  lbend:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - language-bender

tests:
  lang-bender-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - language-bender
